import type { Metadata } from "next";

import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const poppings = Poppins({
  weight: ["400", "500", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  // display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppings.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
